//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DeviceShop
{
    using System;
    using System.Collections.Generic;
    
    public partial class Accessories
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Accessories()
        {
            this.SpecificationComponents = new HashSet<SpecificationComponents>();
        }
    
        public int AccessoriesId { get; set; }
        public int ArticleId { get; set; }
        public string Name { get; set; }
        public int UnitId { get; set; }
        public Nullable<int> Length { get; set; }
        public int Count { get; set; }
        public int TypeMaterialId { get; set; }
        public decimal Price { get; set; }
    
        public virtual Article Article { get; set; }
        public virtual TypeMaterial TypeMaterial { get; set; }
        public virtual Unit Unit { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SpecificationComponents> SpecificationComponents { get; set; }
    }
}
