//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DeviceShop
{
    using System;
    using System.Collections.Generic;
    
    public partial class Details
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Details()
        {
            this.SpecificationComponents = new HashSet<SpecificationComponents>();
        }
    
        public int DetailsId { get; set; }
        public int ArticleId { get; set; }
        public string Name { get; set; }
        public double Count { get; set; }
        public int UnitId { get; set; }
        public int TypeDetailsId { get; set; }
        public decimal Price { get; set; }
        public Nullable<int> GostId { get; set; }
    
        public virtual Article Article { get; set; }
        public virtual Gost Gost { get; set; }
        public virtual TypeDetails TypeDetails { get; set; }
        public virtual Unit Unit { get; set; }
        public virtual Unit Unit1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SpecificationComponents> SpecificationComponents { get; set; }
    }
}
