//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DeviceShop
{
    using System;
    using System.Collections.Generic;
    
    public partial class Entrance
    {
        public int EntranceId { get; set; }
        public Nullable<System.DateTime> Date { get; set; }
        public Nullable<int> ContractId { get; set; }
        public string NameItem { get; set; }
        public Nullable<int> Count { get; set; }
        public Nullable<int> CostOne { get; set; }
        public Nullable<int> CostTotal { get; set; }
    
        public virtual Contract Contract { get; set; }
    }
}
