//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DeviceShop
{
    using System;
    using System.Collections.Generic;
    
    public partial class EquipmentFailure
    {
        public int Id { get; set; }
        public int EquipmentId { get; set; }
        public int FailureReasonId { get; set; }
        public System.DateTime StartTime { get; set; }
        public Nullable<System.DateTime> EndTime { get; set; }
        public string Notes { get; set; }
        public string ReportedBy { get; set; }
        public string FixedBy { get; set; }
    
        public virtual Equipment Equipment { get; set; }
        public virtual FailureReason FailureReason { get; set; }
    }
}
