//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DeviceShop
{
    using System;
    using System.Collections.Generic;
    
    public partial class SpecificationOperations
    {
        public int OperationId { get; set; }
        public int SpecificationId { get; set; }
        public int EquipmentId { get; set; }
        public int SequenceNumber { get; set; }
        public string Duration { get; set; }
        public string Description { get; set; }
    
        public virtual Equipment Equipment { get; set; }
        public virtual Specifications Specifications { get; set; }
    }
}
